---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - jupyter-minimal-notebook-imagestream.yaml

commonLabels:
  opendatahub.io/component: "true"
  component.opendatahub.io/name: notebooks

configMapGenerator:
  - name: notebooks-parameters
    env: params.env
  - name: notebook
    env: commit.env
generatorOptions:
  disableNameSuffixHash: true
vars:
  - name: odh-minimal-notebook-image-n
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-minimal-notebook-image-n
  - name: odh-minimal-notebook-image-n-1
    objref:
      kind: ConfigMap
      name: notebooks-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-minimal-notebook-image-n-1
  - name: odh-minimal-notebook-image-commit-n
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-minimal-notebook-image-commit-n
  - name: odh-minimal-notebook-image-commit-n-1
    objref:
      kind: ConfigMap
      name: notebook
      apiVersion: v1
    fieldref:
      fieldpath: data.odh-minimal-notebook-image-commit-n-1

configurations:
  - params.yaml
  - commit.yaml
